export const ONE_MINUTE_IN_MILISECONDS = 1000 * 60;
export const ONE_HOUR_IN_MILISECONDS = ONE_MINUTE_IN_MILISECONDS * 60;
export const ONE_DAY_IN_MILISECONDS = ONE_HOUR_IN_MILISECONDS * 24;
export const ANNOUNCEMENT_AGE_DAYS = 3;
